# Generated by Django 6.1.1 on 2026-09-21 12:39

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Journal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('content', models.TextField()),
                ('entry_date', models.DateField(default=django.utils.timezone.localdate)),
            ],
            options={
                'ordering': ['-entry_date', '-id'],
            },
        ),
    ]
